accelerate launch examples/qwen_image/model_training/train.py \
  --dataset_base_path "prepared_data_original" \
  --dataset_metadata_path "prepared_data_original/metadata.json" \
  --data_file_keys "image,edit_image" \
  --height 512 --width 512 \
  --dataset_repeat 1 \
  --model_id_with_origin_paths "Qwen/Qwen-Image-Edit-2509:transformer/diffusion_pytorch_model*.safetensors,Qwen/Qwen-Image:text_encoder/model*.safetensors,Qwen/Qwen-Image:vae/diffusion_pytorch_model.safetensors" \
  --learning_rate 1e-4 \
  --num_epochs 5 \
  --save_steps 1000 \
  --output_path "train/Qwen-Image-Edit-2509_inpaint_lora" \
  --lora_base_model "dit" \
  --lora_target_modules "to_q,to_k,to_v,add_q_proj,add_k_proj,add_v_proj,to_out.0,to_add_out,img_mlp.net.2,img_mod.1,txt_mlp.net.2,txt_mod.1" \
  --lora_rank 64 \
  --extra_inputs "edit_image" \
  --find_unused_parameters \
  --dataset_num_workers 8 \
  --use_gradient_checkpointing \
  --gradient_accumulation_steps 8 \
  --wandb_project "qwen-image-inpaint" \
  --wandb_name "lora-rank64-lr1e4"